### ISSUE TITLE
Add Chris G's table as a data table to Water Resources page

### ISSUE THREAD

**Issue by HGray-EA** [HGray-EA/Evidence_Packs#11]
Could you insert Chris' spreadsheet on line 227 of Water_Resources.qmd as a DT datatable like above table in doc

Here's link to file location in databricks: 

/dbfs/FileStore/WSX_HGray/ETL_Imports_Require_Manual/WR_for_Parrett_evidence_pack.xlsx

**Comment by JVaughan1101** [comment]
I've added this data table and committed the changes to a new branch called Water_Resources_Updates

**Comment by HGray-EA** [comment]
Thanks @JVaughan1101, I can see the new branch but can't see any commits, can you make sure you've pushed your commits to the right branch: Should be: 

git checkout -b Water_Resources_Updates (you're on desired branch)

[make changes]

git commit -m "Added DT table" Water_Resources.qmd

git push origin Water_Resources_Updates

Thanks ☺️
