### ISSUE TITLE
Add groundwater catchments to Overview.qmd page as leaflet map

### ISSUE THREAD

**Issue by HGray-EA** [HGray-EA/Evidence_Packs#12]
Not sure if better in Overview.qmd page or Water_Resources.qmd Page - will have to see which is busier 

Would like this to be in same design as wb leaflet plot at top of Overview.qmd page.

Please add this GW catchment leaflet map to line 223 of Water_Resources.qmd, we'll see if it works okay with flow of document there

Here's the location for GW catchments shapefile for all GW OPCATs in England:
/dbfs/FileStore/WSX_HGray/ETL_Imports_Require_Manual/WFD_Groundwater_Operational_Catchments_Cycle_3.shp

**Comment by JVaughan1101** [comment]
I've added a map which displays the groundwater catchments within the Parrett - did we want all groundwater catchments in Wessex or just those in the Parrett? 

I've put this map in the Overview.qmd page as there was a note in this to 'add GW map here' but happy to move it into the Water_Resources.qmd page if this seems a better pace for it.

**Comment by HGray-EA** [comment]
Cheers that's great, I will move it to the water resources page as it's a bit plot light on that page
